/*
###############################################################
#  Generated by:      Cadence Innovus 20.15-s105_1
#  OS:                Linux x86_64(Host ID linux28)
#  Generated on:      Thu May 19 22:51:06 2022
#  Design:            CHIP
#  Command:           saveNetlist CHIP.v
###############################################################
*/
module LBP (
	clk, 
	rst_n, 
	in_valid, 
	in_image, 
	out_valid, 
	out_image);
   input clk;
   input rst_n;
   input in_valid;
   input [7:0] in_image;
   output out_valid;
   output [7:0] out_image;

   // Internal wires
   wire CTS_1;
   wire FE_OCPN14_C_out_image_2;
   wire FE_OCPN13_C_out_image_1;
   wire FE_OFN12_C_rst_n;
   wire FE_OFN7_n537;
   wire FE_OFN6_n537;
   wire FE_OFN5_C_out_image_3;
   wire FE_OFN4_C_out_image_4;
   wire FE_OFN3_C_out_image_5;
   wire FE_OFN2_C_out_image_6;
   wire FE_OFN1_C_out_image_7;
   wire FE_OFN0_C_rst_n;
   wire finish_all;
   wire N170;
   wire N171;
   wire N172;
   wire N212;
   wire N213;
   wire N214;
   wire N215;
   wire N216;
   wire N217;
   wire N218;
   wire N219;
   wire N220;
   wire N221;
   wire N222;
   wire N223;
   wire write_en;
   wire N226;
   wire N227;
   wire N228;
   wire N229;
   wire N230;
   wire N231;
   wire N232;
   wire N233;
   wire N1887;
   wire N1888;
   wire N1889;
   wire N1890;
   wire N1891;
   wire N1892;
   wire N1893;
   wire N1894;
   wire N1895;
   wire N1896;
   wire N1897;
   wire N1898;
   wire N1899;
   wire N1900;
   wire N1901;
   wire N1902;
   wire N1903;
   wire N1904;
   wire N1905;
   wire N1906;
   wire N1907;
   wire N1908;
   wire N1909;
   wire N1910;
   wire N1911;
   wire N1912;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire C1_DATA6_4;
   wire C1_DATA6_3;
   wire C1_DATA6_2;
   wire C1_DATA6_1;
   wire C1_DATA6_0;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n292;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n480;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n486;
   wire n487;
   wire n488;
   wire n489;
   wire n490;
   wire n491;
   wire n493;
   wire n494;
   wire n495;
   wire n496;
   wire n497;
   wire n498;
   wire n499;
   wire n500;
   wire n501;
   wire n502;
   wire n503;
   wire n504;
   wire n506;
   wire n507;
   wire n508;
   wire n509;
   wire n510;
   wire n511;
   wire n512;
   wire n513;
   wire n515;
   wire n516;
   wire n517;
   wire n518;
   wire n520;
   wire n521;
   wire n522;
   wire n523;
   wire n524;
   wire n525;
   wire n526;
   wire n527;
   wire n528;
   wire n529;
   wire n530;
   wire n531;
   wire n532;
   wire n535;
   wire n536;
   wire n537;
   wire n538;
   wire n539;
   wire n540;
   wire n541;
   wire n542;
   wire n543;
   wire n544;
   wire n545;
   wire n546;
   wire n547;
   wire n548;
   wire [1:0] state;
   wire [1:0] next_state;
   wire [3:0] counter_block;
   wire [9:5] i;
   wire [9:0] A;
   wire [7:0] D;
   wire [7:0] center;
   wire [7:0] block;
   wire [7:0] Q;

   OAI21X1 FE_RC_4_0 (.A0(n413),
	.A1(n414),
	.B0(n426),
	.Y(n422));
   BUFX2 FE_OFC21_FE_OFN1_C_out_image_7 (.A(FE_OFN1_C_out_image_7),
	.Y(out_image[7]));
   BUFX2 FE_OFC20_FE_OFN2_C_out_image_6 (.A(FE_OFN2_C_out_image_6),
	.Y(out_image[6]));
   BUFX2 FE_OFC19_FE_OFN3_C_out_image_5 (.A(FE_OFN3_C_out_image_5),
	.Y(out_image[5]));
   BUFX2 FE_OFC18_FE_OFN4_C_out_image_4 (.A(FE_OFN4_C_out_image_4),
	.Y(out_image[4]));
   BUFX4 FE_OFC17_FE_OFN5_C_out_image_3 (.A(FE_OFN5_C_out_image_3),
	.Y(out_image[3]));
   CLKBUFX16 CTS_ccl_a_buf_00003 (.A(clk),
	.Y(CTS_1));
   BUFX2 FE_OCPC16_C_out_image_2 (.A(FE_OCPN14_C_out_image_2),
	.Y(out_image[2]));
   BUFX2 FE_OCPC15_C_out_image_1 (.A(FE_OCPN13_C_out_image_1),
	.Y(out_image[1]));
   BUFX1 FE_OFC14_C_rst_n (.A(rst_n),
	.Y(FE_OFN12_C_rst_n));
   MXI2X1 FE_RC_3_0 (.S0(n204),
	.B(n448),
	.A(n219),
	.Y(n435));
   OAI21X1 FE_RC_2_0 (.A0(n418),
	.A1(n420),
	.B0(n439),
	.Y(n383));
   OAI21X1 FE_RC_1_0 (.A0(n427),
	.A1(n284),
	.B0(n439),
	.Y(n386));
   OAI21X1 FE_RC_0_0 (.A0(n427),
	.A1(n284),
	.B0(n356),
	.Y(n359));
   BUFX2 FE_OFC9_n537 (.A(n448),
	.Y(FE_OFN7_n537));
   INVX2 FE_OFC8_n537 (.A(n448),
	.Y(FE_OFN6_n537));
   INVX2 FE_OFC7_n537 (.A(n537),
	.Y(n448));
   BUFX2 FE_OFC6_C_rst_n (.A(rst_n),
	.Y(FE_OFN0_C_rst_n));
   RA1SH mem (.Q(Q),
	.CLK(CTS_1),
	.CEN(1'b0),
	.OEN(1'b0),
	.WEN(write_en),
	.A({ A[9],
		A[8],
		A[7],
		A[6],
		A[5],
		A[4],
		A[3],
		A[2],
		n199,
		A[0] }),
	.D(D));
   DFFX1 block_reg_4_ (.D(n185),
	.CK(CTS_1),
	.Q(block[4]),
	.QN(n545));
   DFFX1 block_reg_2_ (.D(n187),
	.CK(CTS_1),
	.Q(block[2]),
	.QN(n543));
   DFFX1 block_reg_1_ (.D(n188),
	.CK(CTS_1),
	.Q(block[1]),
	.QN(n542));
   DFFX1 block_reg_3_ (.D(n186),
	.CK(CTS_1),
	.Q(block[3]),
	.QN(n544));
   DFFRHQXL D_reg_7_ (.D(N233),
	.CK(CTS_1),
	.RN(FE_OFN0_C_rst_n),
	.Q(D[7]));
   DFFRHQXL D_reg_6_ (.D(N232),
	.CK(CTS_1),
	.RN(FE_OFN0_C_rst_n),
	.Q(D[6]));
   DFFRHQXL D_reg_5_ (.D(N231),
	.CK(CTS_1),
	.RN(FE_OFN0_C_rst_n),
	.Q(D[5]));
   DFFRHQXL D_reg_4_ (.D(N230),
	.CK(CTS_1),
	.RN(FE_OFN0_C_rst_n),
	.Q(D[4]));
   DFFRHQXL D_reg_3_ (.D(N229),
	.CK(CTS_1),
	.RN(rst_n),
	.Q(D[3]));
   DFFRHQXL D_reg_2_ (.D(N228),
	.CK(CTS_1),
	.RN(rst_n),
	.Q(D[2]));
   DFFRHQXL D_reg_1_ (.D(N227),
	.CK(CTS_1),
	.RN(rst_n),
	.Q(D[1]));
   DFFRHQXL D_reg_0_ (.D(N226),
	.CK(CTS_1),
	.RN(rst_n),
	.Q(D[0]));
   DFFRHQXL center_reg_0_ (.D(N1897),
	.CK(CTS_1),
	.RN(rst_n),
	.Q(center[0]));
   DFFRHQXL center_reg_5_ (.D(N1902),
	.CK(CTS_1),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[5]));
   DFFRHQXL center_reg_2_ (.D(N1899),
	.CK(CTS_1),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[2]));
   DFFRHQXL center_reg_6_ (.D(N1903),
	.CK(CTS_1),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[6]));
   DFFRHQXL center_reg_4_ (.D(N1901),
	.CK(CTS_1),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[4]));
   DFFRHQXL center_reg_1_ (.D(N1898),
	.CK(CTS_1),
	.RN(rst_n),
	.Q(center[1]));
   DFFRHQXL center_reg_7_ (.D(N1904),
	.CK(CTS_1),
	.RN(FE_OFN0_C_rst_n),
	.Q(center[7]));
   DFFRHQXL center_reg_3_ (.D(N1900),
	.CK(CTS_1),
	.RN(rst_n),
	.Q(center[3]));
   DFFRHQXL out_image_reg_7_ (.D(N1912),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(FE_OFN1_C_out_image_7));
   DFFRHQXL out_image_reg_6_ (.D(N1911),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(FE_OFN2_C_out_image_6));
   DFFRHQXL out_image_reg_5_ (.D(N1910),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(FE_OFN3_C_out_image_5));
   DFFRHQXL out_image_reg_4_ (.D(N1909),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(FE_OFN4_C_out_image_4));
   DFFRHQXL out_image_reg_3_ (.D(N1908),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(FE_OFN5_C_out_image_3));
   DFFRHQXL out_image_reg_2_ (.D(N1907),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(FE_OCPN14_C_out_image_2));
   DFFRHQXL out_image_reg_1_ (.D(N1906),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(FE_OCPN13_C_out_image_1));
   DFFRHQXL out_image_reg_0_ (.D(N1905),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(out_image[0]));
   DFFRHQXL i_reg_2_ (.D(N216),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(C1_DATA6_2));
   DFFRHQXL finish_all_reg (.D(N212),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(finish_all));
   DFFRHQXL counter_block_reg_3_ (.D(N172),
	.CK(CTS_1),
	.RN(rst_n),
	.Q(counter_block[3]));
   DFFRHQXL i_reg_7_ (.D(N221),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(i[7]));
   DFFRHQXL i_reg_3_ (.D(N217),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(C1_DATA6_3));
   DFFRHQXL i_reg_9_ (.D(N223),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(i[9]));
   DFFRHQXL i_reg_0_ (.D(N214),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(C1_DATA6_0));
   DFFRHQXL i_reg_4_ (.D(N218),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(C1_DATA6_4));
   DFFRHQX1 i_reg_1_ (.D(N215),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(C1_DATA6_1));
   DFFRHQX4 out_valid_reg (.D(N213),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(out_valid));
   DFFRHQX1 counter_block_reg_0_ (.D(n548),
	.CK(CTS_1),
	.RN(rst_n),
	.Q(counter_block[0]));
   DFFRHQX1 i_reg_8_ (.D(N222),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(i[8]));
   DFFRHQX1 counter_block_reg_2_ (.D(N171),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(counter_block[2]));
   DFFHQX1 block_reg_5_ (.D(n184),
	.CK(CTS_1),
	.Q(block[5]));
   DFFRX1 state_reg_1_ (.D(next_state[1]),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(state[1]),
	.QN(n535));
   DFFX1 block_reg_6_ (.D(n183),
	.CK(CTS_1),
	.Q(block[6]),
	.QN(n546));
   DFFX1 block_reg_0_ (.D(n189),
	.CK(CTS_1),
	.Q(block[0]),
	.QN(n541));
   DFFX1 block_reg_7_ (.D(n182),
	.CK(CTS_1),
	.Q(block[7]),
	.QN(n547));
   DFFRX1 state_reg_0_ (.D(next_state[0]),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(state[0]),
	.QN(n536));
   DFFSX1 write_en_reg (.D(FE_OFN6_n537),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(write_en));
   DFFSX1 A_reg_0_ (.D(N1887),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[0]),
	.QN(n202));
   DFFSXL A_reg_2_ (.D(N1889),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[2]),
	.QN(n201));
   DFFSX1 A_reg_1_ (.D(N1888),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(n199),
	.QN(n532));
   DFFSXL A_reg_6_ (.D(N1893),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[6]),
	.QN(n540));
   DFFSX1 A_reg_4_ (.D(N1891),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[4]),
	.QN(n538));
   DFFSX1 A_reg_8_ (.D(N1895),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[8]));
   DFFSXL A_reg_9_ (.D(N1896),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[9]));
   DFFSX1 A_reg_3_ (.D(N1890),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[3]),
	.QN(n200));
   DFFSX1 A_reg_5_ (.D(N1892),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[5]),
	.QN(n539));
   DFFSX1 A_reg_7_ (.D(N1894),
	.CK(CTS_1),
	.SN(FE_OFN0_C_rst_n),
	.Q(A[7]));
   DFFRHQX1 counter_block_reg_1_ (.D(N170),
	.CK(CTS_1),
	.RN(rst_n),
	.Q(counter_block[1]));
   DFFRHQX1 i_reg_5_ (.D(N219),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(i[5]));
   DFFRHQXL i_reg_6_ (.D(N220),
	.CK(CTS_1),
	.RN(FE_OFN12_C_rst_n),
	.Q(i[6]));
   NOR2X1 U254 (.A(n210),
	.B(n204),
	.Y(n526));
   NOR2X1 U255 (.A(n529),
	.B(counter_block[0]),
	.Y(n548));
   NOR2X1 U256 (.A(n204),
	.B(n511),
	.Y(n438));
   NAND2BX1 U257 (.AN(n279),
	.B(n278),
	.Y(n430));
   NOR2X1 U259 (.A(n332),
	.B(n441),
	.Y(n486));
   AND2X1 U260 (.A(n277),
	.B(n276),
	.Y(n278));
   NAND2BX1 U261 (.AN(next_state[1]),
	.B(next_state[0]),
	.Y(n537));
   NOR2X1 U262 (.A(n496),
	.B(n252),
	.Y(n253));
   NOR2X1 U263 (.A(C1_DATA6_2),
	.B(C1_DATA6_3),
	.Y(n368));
   NOR2X1 U264 (.A(C1_DATA6_0),
	.B(C1_DATA6_1),
	.Y(n369));
   NOR2X1 U265 (.A(n223),
	.B(n235),
	.Y(n513));
   NOR2X1 U266 (.A(n467),
	.B(counter_block[1]),
	.Y(n234));
   NOR2X1 U267 (.A(C1_DATA6_1),
	.B(C1_DATA6_2),
	.Y(n232));
   NOR2X1 U268 (.A(n506),
	.B(n226),
	.Y(n227));
   XNOR2XL U269 (.A(n330),
	.B(n540),
	.Y(n343));
   OAI2BB1XL U270 (.A0N(A[3]),
	.A1N(n435),
	.B0(n293),
	.Y(N1890));
   OAI2BB1XL U271 (.A0N(A[7]),
	.A1N(n435),
	.B0(n408),
	.Y(N1894));
   OAI2BB1XL U272 (.A0N(A[4]),
	.A1N(n435),
	.B0(n380),
	.Y(N1891));
   OAI2BB1XL U273 (.A0N(A[2]),
	.A1N(n435),
	.B0(n306),
	.Y(N1889));
   OAI2BB1XL U274 (.A0N(A[8]),
	.A1N(n435),
	.B0(n434),
	.Y(N1895));
   OAI2BB1XL U275 (.A0N(A[6]),
	.A1N(n435),
	.B0(n344),
	.Y(N1893));
   INVX1 U276 (.A(n438),
	.Y(n479));
   AOI2BB1XL U277 (.A0N(n262),
	.A1N(n249),
	.B0(n483),
	.Y(n250));
   OAI31XL U278 (.A0(n483),
	.A1(n257),
	.A2(n209),
	.B0(rst_n),
	.Y(n210));
   XOR2XL U279 (.A(n280),
	.B(n200),
	.Y(n281));
   XNOR2XL U280 (.A(n294),
	.B(n201),
	.Y(n305));
   NOR2X1 U281 (.A(n296),
	.B(C1_DATA6_2),
	.Y(n240));
   INVX1 U282 (.A(n235),
	.Y(n265));
   NAND2X1 U283 (.A(n203),
	.B(state[1]),
	.Y(n216));
   CLKINVX2 U284 (.A(n214),
	.Y(n436));
   NAND2XL U285 (.A(C1_DATA6_3),
	.B(C1_DATA6_4),
	.Y(n226));
   AOI22XL U287 (.A0(n414),
	.A1(C1_DATA6_0),
	.B0(n413),
	.B1(n356),
	.Y(n358));
   NAND2X1 U288 (.A(n382),
	.B(n381),
	.Y(n407));
   NAND2X1 U289 (.A(n493),
	.B(n227),
	.Y(n260));
   OAI211X1 U290 (.A0(n381),
	.A1(n508),
	.B0(n289),
	.C0(n288),
	.Y(n290));
   NOR2X1 U291 (.A(n531),
	.B(counter_block[2]),
	.Y(n437));
   AOI211X1 U292 (.A0(i[5]),
	.A1(n407),
	.B0(n390),
	.C0(n389),
	.Y(n391));
   OAI211X1 U293 (.A0(n436),
	.A1(n208),
	.B0(n500),
	.C0(rst_n),
	.Y(n528));
   INVX2 U294 (.A(n479),
	.Y(n198));
   INVXL U296 (.A(n262),
	.Y(n270));
   NAND2XL U297 (.A(i[5]),
	.B(i[6]),
	.Y(n310));
   XNOR2XL U298 (.A(i[9]),
	.B(n313),
	.Y(n323));
   OR2XL U299 (.A(n412),
	.B(i[8]),
	.Y(n313));
   NAND2XL U300 (.A(n515),
	.B(n236),
	.Y(n237));
   NOR4XL U301 (.A(n270),
	.B(n264),
	.C(n245),
	.D(n235),
	.Y(n236));
   AND2X1 U302 (.A(n515),
	.B(n253),
	.Y(n418));
   AND2X1 U303 (.A(n515),
	.B(n244),
	.Y(n414));
   AOI2BB1X1 U304 (.A0N(n243),
	.A1N(n242),
	.B0(n272),
	.Y(n244));
   AOI21XL U305 (.A0(n241),
	.A1(counter_block[0]),
	.B0(n481),
	.Y(n243));
   AND2X1 U306 (.A(n515),
	.B(n248),
	.Y(n413));
   INVX2 U307 (.A(n382),
	.Y(n411));
   OR2X1 U308 (.A(n204),
	.B(n480),
	.Y(n495));
   INVXL U309 (.A(n369),
	.Y(n296));
   NAND4X1 U310 (.A(n232),
	.B(n356),
	.C(n508),
	.D(n447),
	.Y(n262));
   NAND4XL U311 (.A(n220),
	.B(n442),
	.C(n488),
	.D(n439),
	.Y(n264));
   NAND2X1 U312 (.A(n264),
	.B(n265),
	.Y(n272));
   NAND2X1 U313 (.A(C1_DATA6_1),
	.B(C1_DATA6_0),
	.Y(n365));
   INVXL U314 (.A(n365),
	.Y(n295));
   XOR2XL U315 (.A(n506),
	.B(n508),
	.Y(n292));
   AOI22XL U316 (.A0(n284),
	.A1(n287),
	.B0(n427),
	.B1(n292),
	.Y(n288));
   NAND2XL U317 (.A(n239),
	.B(n287),
	.Y(n256));
   NAND2XL U318 (.A(n411),
	.B(n497),
	.Y(n321));
   AOI22XL U319 (.A0(n414),
	.A1(n323),
	.B0(n413),
	.B1(n323),
	.Y(n319));
   AOI22XL U320 (.A0(n284),
	.A1(n324),
	.B0(n427),
	.B1(n323),
	.Y(n325));
   AOI22XL U321 (.A0(n284),
	.A1(n375),
	.B0(n427),
	.B1(n445),
	.Y(n376));
   NAND4XL U322 (.A(n374),
	.B(n373),
	.C(n372),
	.D(n371),
	.Y(n378));
   NAND2XL U323 (.A(n411),
	.B(n445),
	.Y(n374));
   NAND2XL U324 (.A(n227),
	.B(n257),
	.Y(n258));
   NOR2X1 U325 (.A(n230),
	.B(n229),
	.Y(n382));
   OAI21XL U326 (.A0(n259),
	.A1(n225),
	.B0(n224),
	.Y(n230));
   OAI31XL U328 (.A0(counter_block[1]),
	.A1(counter_block[2]),
	.A2(counter_block[0]),
	.B0(counter_block[3]),
	.Y(n219));
   NAND3BXL U329 (.AN(state[0]),
	.B(out_valid),
	.C(finish_all),
	.Y(n203));
   AOI21XL U330 (.A0(n227),
	.A1(i[5]),
	.B0(i[6]),
	.Y(n332));
   XOR2XL U331 (.A(n410),
	.B(i[8]),
	.Y(n518));
   INVXL U332 (.A(C1_DATA6_4),
	.Y(n447));
   NAND2XL U333 (.A(n438),
	.B(C1_DATA6_0),
	.Y(n503));
   XOR2XL U334 (.A(n312),
	.B(n499),
	.Y(n497));
   NAND2XL U335 (.A(n410),
	.B(i[8]),
	.Y(n312));
   INVXL U336 (.A(C1_DATA6_3),
	.Y(n508));
   INVXL U337 (.A(n331),
	.Y(n441));
   NAND2X1 U338 (.A(n510),
	.B(n207),
	.Y(n529));
   NAND2XL U339 (.A(n206),
	.B(counter_block[3]),
	.Y(n207));
   NAND2XL U340 (.A(n214),
	.B(n205),
	.Y(n206));
   INVXL U341 (.A(n231),
	.Y(n223));
   NAND2X1 U342 (.A(n437),
	.B(n233),
	.Y(n468));
   NAND2X1 U343 (.A(n515),
	.B(n265),
	.Y(n204));
   INVX2 U344 (.A(n204),
	.Y(n510));
   NAND2XL U345 (.A(n437),
	.B(n436),
	.Y(n511));
   OAI22XL U346 (.A0(n462),
	.A1(n461),
	.B0(block[7]),
	.B1(n460),
	.Y(n480));
   OAI22XL U347 (.A0(center[7]),
	.A1(n547),
	.B0(center[6]),
	.B1(n546),
	.Y(n461));
   AOI21XL U348 (.A0(n459),
	.A1(n458),
	.B0(n457),
	.Y(n462));
   OR2XL U349 (.A(i[5]),
	.B(i[6]),
	.Y(n392));
   OR2XL U350 (.A(n392),
	.B(i[7]),
	.Y(n412));
   NAND3X1 U351 (.A(n515),
	.B(n271),
	.C(n262),
	.Y(n283));
   INVXL U352 (.A(n271),
	.Y(n252));
   NAND2XL U353 (.A(n266),
	.B(n234),
	.Y(n245));
   NAND2XL U354 (.A(n266),
	.B(n436),
	.Y(n285));
   AND2XL U355 (.A(n396),
	.B(i[7]),
	.Y(n416));
   XNOR2XL U356 (.A(i[8]),
	.B(n412),
	.Y(n426));
   AND2XL U357 (.A(n369),
	.B(n368),
	.Y(n370));
   OAI2BB1XL U358 (.A0N(n269),
	.A1N(n268),
	.B0(n515),
	.Y(n277));
   NAND4XL U359 (.A(n267),
	.B(n266),
	.C(n467),
	.D(n265),
	.Y(n268));
   NAND2XL U360 (.A(n263),
	.B(n513),
	.Y(n269));
   OAI2BB1XL U361 (.A0N(n275),
	.A1N(n274),
	.B0(n515),
	.Y(n276));
   NAND3XL U362 (.A(n273),
	.B(n475),
	.C(n227),
	.Y(n274));
   NAND3XL U363 (.A(n271),
	.B(n472),
	.C(n270),
	.Y(n275));
   NAND2XL U364 (.A(n515),
	.B(n221),
	.Y(n259));
   NAND3XL U365 (.A(n515),
	.B(n493),
	.C(n513),
	.Y(n224));
   NAND2X1 U366 (.A(n515),
	.B(n228),
	.Y(n286));
   NAND2XL U367 (.A(n227),
	.B(n311),
	.Y(n331));
   INVXL U368 (.A(n310),
	.Y(n311));
   NAND3XL U369 (.A(i[7]),
	.B(i[8]),
	.C(i[9]),
	.Y(n222));
   NOR3BXL U370 (.AN(counter_block[2]),
	.B(counter_block[3]),
	.C(counter_block[0]),
	.Y(n282));
   OAI2BB1XL U371 (.A0N(n455),
	.A1N(n454),
	.B0(n453),
	.Y(n459));
   AOI22XL U372 (.A0(center[3]),
	.A1(n544),
	.B0(n545),
	.B1(center[4]),
	.Y(n453));
   AOI2BB2XL U373 (.A0N(center[2]),
	.A1N(n543),
	.B0(n449),
	.B1(block[3]),
	.Y(n455));
   OAI211XL U374 (.A0(block[1]),
	.A1(n452),
	.B0(n451),
	.C0(n450),
	.Y(n454));
   AOI2BB2XL U375 (.A0N(center[4]),
	.A1N(n545),
	.B0(n456),
	.B1(block[5]),
	.Y(n458));
   OAI2BB2XL U376 (.A0N(center[6]),
	.A1N(n546),
	.B0(n456),
	.B1(block[5]),
	.Y(n457));
   NAND2XL U377 (.A(n266),
	.B(counter_block[1]),
	.Y(n481));
   INVXL U378 (.A(n282),
	.Y(n261));
   NAND2XL U379 (.A(n285),
	.B(n477),
	.Y(n257));
   AOI22XL U380 (.A0(n284),
	.A1(n393),
	.B0(n427),
	.B1(n394),
	.Y(n402));
   AOI22XL U381 (.A0(n420),
	.A1(n398),
	.B0(n418),
	.B1(n397),
	.Y(n399));
   AOI22XL U382 (.A0(n414),
	.A1(n394),
	.B0(n413),
	.B1(n394),
	.Y(n400));
   NAND2XL U383 (.A(n239),
	.B(i[5]),
	.Y(n385));
   AOI22XL U384 (.A0(n414),
	.A1(n439),
	.B0(n413),
	.B1(n439),
	.Y(n384));
   NAND2XL U385 (.A(n411),
	.B(n518),
	.Y(n424));
   AOI22XL U386 (.A0(n420),
	.A1(n419),
	.B0(n418),
	.B1(n417),
	.Y(n421));
   AOI22XL U388 (.A0(n284),
	.A1(n428),
	.B0(n427),
	.B1(n426),
	.Y(n429));
   AOI22XL U389 (.A0(n284),
	.A1(n339),
	.B0(n427),
	.B1(n338),
	.Y(n340));
   NAND4XL U390 (.A(n337),
	.B(n336),
	.C(n335),
	.D(n334),
	.Y(n342));
   AOI22XL U391 (.A0(n414),
	.A1(n338),
	.B0(n413),
	.B1(n338),
	.Y(n335));
   AOI22XL U392 (.A0(n420),
	.A1(n333),
	.B0(n418),
	.B1(n339),
	.Y(n334));
   NAND2XL U393 (.A(n411),
	.B(n486),
	.Y(n337));
   AOI22XL U394 (.A0(n284),
	.A1(n350),
	.B0(n427),
	.B1(n349),
	.Y(n351));
   NAND4XL U395 (.A(n348),
	.B(n347),
	.C(n346),
	.D(n345),
	.Y(n353));
   NAND2XL U396 (.A(n411),
	.B(n349),
	.Y(n348));
   AOI22XL U397 (.A0(n284),
	.A1(n301),
	.B0(n427),
	.B1(n489),
	.Y(n302));
   NAND4XL U398 (.A(n300),
	.B(n299),
	.C(n298),
	.D(n297),
	.Y(n304));
   AOI22XL U399 (.A0(n414),
	.A1(C1_DATA6_2),
	.B0(n413),
	.B1(n301),
	.Y(n298));
   NAND2XL U400 (.A(n411),
	.B(n489),
	.Y(n300));
   NAND2XL U401 (.A(counter_block[0]),
	.B(counter_block[1]),
	.Y(n214));
   INVXL U402 (.A(i[5]),
	.Y(n439));
   XOR2XL U403 (.A(n367),
	.B(n447),
	.Y(n445));
   OR2XL U404 (.A(n366),
	.B(n365),
	.Y(n367));
   INVXL U405 (.A(i[9]),
	.Y(n499));
   INVXL U406 (.A(i[7]),
	.Y(n442));
   NAND2XL U407 (.A(n436),
	.B(counter_block[2]),
	.Y(n530));
   XNOR2XL U408 (.A(n295),
	.B(n491),
	.Y(n489));
   NAND2BX1 U409 (.AN(n261),
	.B(n233),
	.Y(n474));
   NAND4BXL U410 (.AN(counter_block[3]),
	.B(n233),
	.C(counter_block[2]),
	.D(counter_block[0]),
	.Y(n477));
   NAND2XL U411 (.A(n282),
	.B(counter_block[1]),
	.Y(n466));
   INVXL U412 (.A(n483),
	.Y(n485));
   NOR2X1 U413 (.A(n468),
	.B(counter_block[0]),
	.Y(n493));
   INVXL U414 (.A(n493),
	.Y(n496));
   NAND3XL U415 (.A(n437),
	.B(counter_block[1]),
	.C(n467),
	.Y(n464));
   NAND3XL U416 (.A(n261),
	.B(n468),
	.C(n464),
	.Y(n209));
   INVXL U417 (.A(n266),
	.Y(n208));
   OAI2BB1XL U418 (.A0N(A[5]),
	.A1N(n435),
	.B0(n391),
	.Y(N1892));
   AND2XL U419 (.A(FE_OFN7_n537),
	.B(n388),
	.Y(n389));
   NAND4XL U420 (.A(n386),
	.B(n385),
	.C(n384),
	.D(n383),
	.Y(n390));
   AOI211X1 U421 (.A0(n292),
	.A1(n411),
	.B0(n291),
	.C0(n290),
	.Y(n293));
   NAND3XL U422 (.A(n256),
	.B(n255),
	.C(n254),
	.Y(n291));
   OAI2BB1XL U423 (.A0N(A[9]),
	.A1N(n435),
	.B0(n329),
	.Y(N1896));
   OAI2BB1XL U424 (.A0N(i[9]),
	.A1N(n430),
	.B0(n325),
	.Y(n326));
   NAND4XL U425 (.A(n321),
	.B(n320),
	.C(n319),
	.D(n318),
	.Y(n327));
   OAI2BB1XL U426 (.A0N(A[0]),
	.A1N(n435),
	.B0(n363),
	.Y(N1887));
   AOI211XL U427 (.A0(FE_OFN7_n537),
	.A1(n202),
	.B0(n362),
	.C0(n361),
	.Y(n363));
   MXI2XL U428 (.S0(C1_DATA6_0),
	.B(n381),
	.A(n382),
	.Y(n361));
   NAND4XL U429 (.A(n360),
	.B(n359),
	.C(n358),
	.D(n357),
	.Y(n362));
   MXI2XL U430 (.S0(state[1]),
	.B(n217),
	.A(n218),
	.Y(next_state[0]));
   NAND3BXL U431 (.AN(finish_all),
	.B(n536),
	.C(out_valid),
	.Y(n217));
   INVXL U432 (.A(in_valid),
	.Y(n218));
   OAI2BB1X1 U433 (.A0N(block[7]),
	.A1N(n528),
	.B0(n211),
	.Y(n182));
   NAND2XL U434 (.A(Q[7]),
	.B(n526),
	.Y(n211));
   OAI2BB1X1 U435 (.A0N(block[0]),
	.A1N(n528),
	.B0(n213),
	.Y(n189));
   NAND2XL U436 (.A(Q[0]),
	.B(n526),
	.Y(n213));
   OAI2BB1X1 U437 (.A0N(block[6]),
	.A1N(n528),
	.B0(n212),
	.Y(n183));
   NAND2XL U438 (.A(Q[6]),
	.B(n526),
	.Y(n212));
   OAI21XL U439 (.A0(in_valid),
	.A1(n536),
	.B0(n216),
	.Y(next_state[1]));
   OAI2BB1XL U440 (.A0N(block[5]),
	.A1N(n528),
	.B0(n527),
	.Y(n184));
   NAND2XL U441 (.A(Q[5]),
	.B(n526),
	.Y(n527));
   MXI2XL U442 (.S0(n438),
	.B(n487),
	.A(n488),
	.Y(N220));
   XOR2XL U443 (.A(n440),
	.B(n439),
	.Y(N219));
   NAND2XL U444 (.A(n438),
	.B(n227),
	.Y(n440));
   MXI2XL U445 (.S0(n438),
	.B(n520),
	.A(n521),
	.Y(N222));
   INVXL U446 (.A(n518),
	.Y(n520));
   MXI2XL U447 (.S0(counter_block[1]),
	.B(n501),
	.A(n502),
	.Y(N170));
   NAND2XL U448 (.A(n500),
	.B(counter_block[0]),
	.Y(n502));
   OAI2BB1XL U449 (.A0N(out_valid),
	.A1N(n510),
	.B0(n479),
	.Y(N213));
   XOR2XL U450 (.A(n503),
	.B(n444),
	.Y(N215));
   MXI2XL U451 (.S0(n198),
	.B(n446),
	.A(n447),
	.Y(N218));
   INVXL U452 (.A(n445),
	.Y(n446));
   AOI2BB1XL U453 (.A0N(n198),
	.A1N(C1_DATA6_0),
	.B0(n504),
	.Y(N214));
   MXI2XL U454 (.S0(n198),
	.B(n498),
	.A(n499),
	.Y(N223));
   INVXL U455 (.A(n497),
	.Y(n498));
   XOR2XL U456 (.A(n509),
	.B(n508),
	.Y(N217));
   NAND2XL U457 (.A(n438),
	.B(n507),
	.Y(n509));
   XOR2XL U458 (.A(n443),
	.B(n442),
	.Y(N221));
   NAND2XL U459 (.A(n438),
	.B(n441),
	.Y(n443));
   AOI21XL U460 (.A0(n531),
	.A1(n530),
	.B0(n529),
	.Y(N172));
   NAND2XL U461 (.A(n517),
	.B(n516),
	.Y(N212));
   NAND4XL U462 (.A(n515),
	.B(n227),
	.C(n513),
	.D(n512),
	.Y(n516));
   NAND3XL U463 (.A(n510),
	.B(finish_all),
	.C(n511),
	.Y(n517));
   MXI2XL U464 (.S0(n198),
	.B(n490),
	.A(n491),
	.Y(N216));
   INVXL U465 (.A(n489),
	.Y(n490));
   OAI2BB2XL U466 (.A0N(out_image[0]),
	.A1N(n473),
	.B0(n474),
	.B1(n495),
	.Y(N1905));
   OAI21XL U467 (.A0(n472),
	.A1(n204),
	.B0(n537),
	.Y(n473));
   OAI2BB2XL U468 (.A0N(out_image[1]),
	.A1N(n476),
	.B0(n477),
	.B1(n495),
	.Y(N1906));
   OAI21XL U469 (.A0(n475),
	.A1(n204),
	.B0(n537),
	.Y(n476));
   OAI2BB2XL U470 (.A0N(out_image[2]),
	.A1N(n465),
	.B0(n466),
	.B1(n495),
	.Y(N1907));
   OAI2BB1XL U471 (.A0N(n466),
	.A1N(n510),
	.B0(n537),
	.Y(n465));
   OAI2BB2XL U472 (.A0N(out_image[3]),
	.A1N(n484),
	.B0(n485),
	.B1(n495),
	.Y(N1908));
   OAI21XL U473 (.A0(n483),
	.A1(n204),
	.B0(n537),
	.Y(n484));
   OAI2BB2XL U474 (.A0N(out_image[4]),
	.A1N(n494),
	.B0(n496),
	.B1(n495),
	.Y(N1909));
   OAI21XL U475 (.A0(n493),
	.A1(n204),
	.B0(n537),
	.Y(n494));
   OAI2BB2XL U476 (.A0N(out_image[5]),
	.A1N(n470),
	.B0(n495),
	.B1(n471),
	.Y(N1910));
   OAI21XL U477 (.A0(n469),
	.A1(n204),
	.B0(n537),
	.Y(n470));
   OAI2BB2XL U478 (.A0N(out_image[6]),
	.A1N(n463),
	.B0(n464),
	.B1(n495),
	.Y(N1911));
   OAI2BB1XL U479 (.A0N(n464),
	.A1N(n510),
	.B0(n537),
	.Y(n463));
   OAI2BB2XL U480 (.A0N(out_image[7]),
	.A1N(n478),
	.B0(n480),
	.B1(n479),
	.Y(N1912));
   OAI2BB1XL U481 (.A0N(n511),
	.A1N(n510),
	.B0(n537),
	.Y(n478));
   AND2XL U482 (.A(n448),
	.B(in_image[0]),
	.Y(N226));
   AND2XL U483 (.A(n448),
	.B(in_image[1]),
	.Y(N227));
   AND2XL U484 (.A(n448),
	.B(in_image[2]),
	.Y(N228));
   AND2XL U485 (.A(n448),
	.B(in_image[3]),
	.Y(N229));
   AND2XL U486 (.A(n448),
	.B(in_image[4]),
	.Y(N230));
   AND2XL U487 (.A(n448),
	.B(in_image[5]),
	.Y(N231));
   AND2XL U488 (.A(n448),
	.B(in_image[6]),
	.Y(N232));
   AND2XL U489 (.A(n448),
	.B(in_image[7]),
	.Y(N233));
   OAI2BB1XL U490 (.A0N(block[3]),
	.A1N(n528),
	.B0(n525),
	.Y(n186));
   NAND2XL U491 (.A(Q[3]),
	.B(n526),
	.Y(n525));
   OAI2BB1XL U492 (.A0N(block[1]),
	.A1N(n528),
	.B0(n524),
	.Y(n188));
   NAND2XL U493 (.A(Q[1]),
	.B(n526),
	.Y(n524));
   OAI2BB1XL U494 (.A0N(block[2]),
	.A1N(n528),
	.B0(n522),
	.Y(n187));
   NAND2XL U495 (.A(Q[2]),
	.B(n526),
	.Y(n522));
   OAI2BB1XL U496 (.A0N(block[4]),
	.A1N(n528),
	.B0(n523),
	.Y(n185));
   NAND2XL U497 (.A(Q[4]),
	.B(n526),
	.Y(n523));
   INVXL U498 (.A(C1_DATA6_2),
	.Y(n491));
   NOR2X1 U501 (.A(counter_block[3]),
	.B(counter_block[2]),
	.Y(n266));
   NAND2X1 U502 (.A(in_valid),
	.B(n216),
	.Y(n515));
   AOI2BB1X1 U503 (.A0N(n535),
	.A1N(out_valid),
	.B0(state[0]),
	.Y(n235));
   INVXL U504 (.A(counter_block[2]),
	.Y(n205));
   INVX2 U505 (.A(n529),
	.Y(n500));
   NOR2X1 U506 (.A(n530),
	.B(counter_block[3]),
	.Y(n483));
   INVXL U507 (.A(counter_block[1]),
	.Y(n233));
   INVXL U508 (.A(counter_block[3]),
	.Y(n531));
   INVXL U509 (.A(counter_block[0]),
	.Y(n467));
   XOR2XL U510 (.A(n214),
	.B(counter_block[2]),
	.Y(n215));
   NOR2X1 U511 (.A(n529),
	.B(n215),
	.Y(N171));
   NAND2X1 U512 (.A(n295),
	.B(C1_DATA6_2),
	.Y(n506));
   NOR2X1 U513 (.A(i[8]),
	.B(i[9]),
	.Y(n220));
   INVX2 U514 (.A(i[6]),
	.Y(n488));
   NOR2X1 U515 (.A(n264),
	.B(n235),
	.Y(n221));
   INVXL U516 (.A(n257),
	.Y(n225));
   NOR2X1 U517 (.A(n222),
	.B(n310),
	.Y(n231));
   NOR2X1 U518 (.A(n227),
	.B(n272),
	.Y(n228));
   NOR2X1 U519 (.A(n286),
	.B(n477),
	.Y(n229));
   NOR2X1 U520 (.A(n231),
	.B(n235),
	.Y(n271));
   INVXL U521 (.A(C1_DATA6_0),
	.Y(n356));
   NAND4XL U522 (.A(n515),
	.B(n513),
	.C(n282),
	.D(n262),
	.Y(n238));
   OAI211X1 U523 (.A0(n283),
	.A1(n474),
	.B0(n238),
	.C0(n237),
	.Y(n239));
   XOR2XL U524 (.A(n240),
	.B(C1_DATA6_3),
	.Y(n287));
   INVXL U525 (.A(n227),
	.Y(n241));
   NOR2X1 U526 (.A(n262),
	.B(n245),
	.Y(n242));
   INVXL U527 (.A(n245),
	.Y(n246));
   NAND2XL U528 (.A(n246),
	.B(n262),
	.Y(n247));
   NOR2X1 U529 (.A(n247),
	.B(n272),
	.Y(n248));
   AOI22XL U530 (.A0(n414),
	.A1(C1_DATA6_3),
	.B0(n413),
	.B1(n287),
	.Y(n255));
   NAND3XL U531 (.A(n531),
	.B(counter_block[2]),
	.C(counter_block[1]),
	.Y(n249));
   AOI21X1 U532 (.A0(n250),
	.A1(n260),
	.B0(n252),
	.Y(n251));
   AND2X1 U533 (.A(n515),
	.B(n251),
	.Y(n420));
   AOI22XL U534 (.A0(n420),
	.A1(C1_DATA6_3),
	.B0(n418),
	.B1(n292),
	.Y(n254));
   NOR2X1 U535 (.A(n259),
	.B(n258),
	.Y(n279));
   OAI211XL U536 (.A0(n262),
	.A1(n261),
	.B0(n260),
	.C0(n485),
	.Y(n263));
   NAND2XL U537 (.A(n264),
	.B(counter_block[1]),
	.Y(n267));
   INVXL U538 (.A(n474),
	.Y(n472));
   INVXL U539 (.A(n272),
	.Y(n273));
   INVXL U540 (.A(n477),
	.Y(n475));
   INVX2 U541 (.A(n430),
	.Y(n381));
   NAND2X1 U542 (.A(n199),
	.B(A[0]),
	.Y(n307));
   INVXL U543 (.A(n307),
	.Y(n294));
   NAND2XL U544 (.A(n294),
	.B(A[2]),
	.Y(n280));
   NAND2X1 U545 (.A(FE_OFN7_n537),
	.B(n281),
	.Y(n289));
   NOR2X1 U546 (.A(n283),
	.B(n466),
	.Y(n284));
   NOR2X1 U547 (.A(n286),
	.B(n285),
	.Y(n427));
   XNOR2XL U548 (.A(n296),
	.B(C1_DATA6_2),
	.Y(n301));
   NAND2XL U549 (.A(n239),
	.B(n301),
	.Y(n299));
   AOI22XL U550 (.A0(n420),
	.A1(C1_DATA6_2),
	.B0(n418),
	.B1(n489),
	.Y(n297));
   OAI2BB1X1 U551 (.A0N(C1_DATA6_2),
	.A1N(n430),
	.B0(n302),
	.Y(n303));
   AOI211X1 U552 (.A0(FE_OFN7_n537),
	.A1(n305),
	.B0(n304),
	.C0(n303),
	.Y(n306));
   NAND2X1 U553 (.A(A[2]),
	.B(A[3]),
	.Y(n308));
   NOR2X1 U554 (.A(n308),
	.B(n307),
	.Y(n364));
   NAND2X1 U555 (.A(n364),
	.B(A[4]),
	.Y(n387));
   NOR2X1 U556 (.A(n387),
	.B(n539),
	.Y(n330));
   AND2X1 U557 (.A(n330),
	.B(A[6]),
	.Y(n403));
   XOR2X1 U558 (.A(n309),
	.B(A[9]),
	.Y(n328));
   NOR2X1 U559 (.A(n331),
	.B(n442),
	.Y(n410));
   NAND2XL U560 (.A(n239),
	.B(i[9]),
	.Y(n320));
   XOR2XL U561 (.A(n314),
	.B(i[9]),
	.Y(n317));
   NOR2X1 U562 (.A(n439),
	.B(n488),
	.Y(n396));
   XOR2XL U563 (.A(n315),
	.B(i[9]),
	.Y(n316));
   AOI22XL U564 (.A0(n420),
	.A1(n317),
	.B0(n418),
	.B1(n316),
	.Y(n318));
   XOR2XL U565 (.A(n322),
	.B(i[9]),
	.Y(n324));
   AOI211X1 U566 (.A0(FE_OFN7_n537),
	.A1(n328),
	.B0(n327),
	.C0(n326),
	.Y(n329));
   NAND2XL U567 (.A(n239),
	.B(i[6]),
	.Y(n336));
   XNOR2XL U568 (.A(i[6]),
	.B(i[5]),
	.Y(n338));
   ADDHXL U569 (.A(i[6]),
	.B(i[5]),
	.S(n333),
	.CO(n395));
   XOR2XL U570 (.A(n439),
	.B(n488),
	.Y(n339));
   OAI2BB1X1 U571 (.A0N(i[6]),
	.A1N(n430),
	.B0(n340),
	.Y(n341));
   AOI211X1 U572 (.A0(FE_OFN7_n537),
	.A1(n343),
	.B0(n342),
	.C0(n341),
	.Y(n344));
   XNOR2XL U573 (.A(n532),
	.B(A[0]),
	.Y(n354));
   XOR2XL U574 (.A(C1_DATA6_0),
	.B(C1_DATA6_1),
	.Y(n349));
   XNOR2XL U575 (.A(C1_DATA6_1),
	.B(C1_DATA6_0),
	.Y(n350));
   NAND2XL U576 (.A(n239),
	.B(n350),
	.Y(n347));
   AOI22XL U577 (.A0(n414),
	.A1(C1_DATA6_1),
	.B0(n413),
	.B1(n350),
	.Y(n346));
   AOI22XL U578 (.A0(n420),
	.A1(C1_DATA6_1),
	.B0(n418),
	.B1(n349),
	.Y(n345));
   OAI2BB1X1 U579 (.A0N(C1_DATA6_1),
	.A1N(n430),
	.B0(n351),
	.Y(n352));
   AOI211X1 U580 (.A0(FE_OFN7_n537),
	.A1(n354),
	.B0(n353),
	.C0(n352),
	.Y(n355));
   OAI2BB1X1 U581 (.A0N(n199),
	.A1N(n435),
	.B0(n355),
	.Y(N1888));
   NAND2XL U582 (.A(n239),
	.B(n356),
	.Y(n360));
   AOI22XL U584 (.A0(n420),
	.A1(C1_DATA6_0),
	.B0(n418),
	.B1(n356),
	.Y(n357));
   XNOR2X1 U585 (.A(n364),
	.B(n538),
	.Y(n379));
   NAND2XL U586 (.A(C1_DATA6_2),
	.B(C1_DATA6_3),
	.Y(n366));
   XOR2XL U587 (.A(n370),
	.B(C1_DATA6_4),
	.Y(n375));
   NAND2XL U588 (.A(n239),
	.B(n375),
	.Y(n373));
   AOI22XL U589 (.A0(n414),
	.A1(C1_DATA6_4),
	.B0(n413),
	.B1(n375),
	.Y(n372));
   AOI22XL U590 (.A0(n420),
	.A1(C1_DATA6_4),
	.B0(n418),
	.B1(n445),
	.Y(n371));
   OAI2BB1X1 U591 (.A0N(C1_DATA6_4),
	.A1N(n430),
	.B0(n376),
	.Y(n377));
   AOI211X1 U592 (.A0(FE_OFN7_n537),
	.A1(n379),
	.B0(n378),
	.C0(n377),
	.Y(n380));
   XOR2X1 U595 (.A(n387),
	.B(n539),
	.Y(n388));
   ADDHXL U596 (.A(i[7]),
	.B(n396),
	.S(n393),
	.CO(n425));
   XNOR2XL U597 (.A(n392),
	.B(i[7]),
	.Y(n394));
   NAND2XL U598 (.A(n239),
	.B(i[7]),
	.Y(n401));
   ADDHXL U599 (.A(i[7]),
	.B(n395),
	.S(n398),
	.CO(n415));
   XNOR2XL U600 (.A(n396),
	.B(n442),
	.Y(n397));
   NAND4X1 U601 (.A(n402),
	.B(n401),
	.C(n400),
	.D(n399),
	.Y(n406));
   ADDHXL U602 (.A(A[7]),
	.B(n403),
	.S(n404),
	.CO(n409));
   AND2X1 U603 (.A(FE_OFN7_n537),
	.B(n404),
	.Y(n405));
   AOI211X1 U604 (.A0(i[7]),
	.A1(n407),
	.B0(n406),
	.C0(n405),
	.Y(n408));
   ADDHXL U605 (.A(A[8]),
	.B(n409),
	.S(n433),
	.CO(n309));
   NAND2XL U606 (.A(n239),
	.B(i[8]),
	.Y(n423));
   ADDHXL U607 (.A(i[8]),
	.B(n415),
	.S(n419),
	.CO(n314));
   ADDHXL U608 (.A(i[8]),
	.B(n416),
	.S(n417),
	.CO(n315));
   NAND4X1 U609 (.A(n424),
	.B(n423),
	.C(n422),
	.D(n421),
	.Y(n432));
   ADDHXL U610 (.A(i[8]),
	.B(n425),
	.S(n428),
	.CO(n322));
   OAI2BB1X1 U611 (.A0N(i[8]),
	.A1N(n430),
	.B0(n429),
	.Y(n431));
   AOI211X1 U612 (.A0(FE_OFN7_n537),
	.A1(n433),
	.B0(n432),
	.C0(n431),
	.Y(n434));
   INVXL U613 (.A(C1_DATA6_1),
	.Y(n444));
   INVXL U614 (.A(center[3]),
	.Y(n449));
   INVXL U615 (.A(center[1]),
	.Y(n452));
   OAI211XL U616 (.A0(center[1]),
	.A1(n542),
	.B0(center[0]),
	.C0(n541),
	.Y(n451));
   NAND2XL U617 (.A(n543),
	.B(center[2]),
	.Y(n450));
   INVXL U618 (.A(center[5]),
	.Y(n456));
   INVXL U619 (.A(center[7]),
	.Y(n460));
   NOR2X1 U620 (.A(n468),
	.B(n467),
	.Y(n469));
   INVXL U621 (.A(n469),
	.Y(n471));
   NOR3X1 U622 (.A(n204),
	.B(counter_block[0]),
	.C(n481),
	.Y(n482));
   MX2XL U623 (.S0(n482),
	.B(Q[0]),
	.A(center[0]),
	.Y(N1897));
   MX2XL U624 (.S0(n482),
	.B(Q[2]),
	.A(center[2]),
	.Y(N1899));
   MX2XL U625 (.S0(n482),
	.B(Q[6]),
	.A(center[6]),
	.Y(N1903));
   MX2XL U626 (.S0(n482),
	.B(Q[4]),
	.A(center[4]),
	.Y(N1901));
   MX2XL U627 (.S0(n482),
	.B(Q[5]),
	.A(center[5]),
	.Y(N1902));
   MX2XL U628 (.S0(n482),
	.B(Q[1]),
	.A(center[1]),
	.Y(N1898));
   MX2XL U629 (.S0(n482),
	.B(Q[7]),
	.A(center[7]),
	.Y(N1904));
   MX2XL U630 (.S0(n482),
	.B(Q[3]),
	.A(center[3]),
	.Y(N1900));
   INVXL U631 (.A(n486),
	.Y(n487));
   INVXL U632 (.A(n548),
	.Y(n501));
   INVXL U633 (.A(n503),
	.Y(n504));
   INVXL U634 (.A(n506),
	.Y(n507));
   INVXL U635 (.A(n511),
	.Y(n512));
   INVXL U636 (.A(i[8]),
	.Y(n521));
endmodule

module CHIP (
	clk, 
	rst_n, 
	in_valid, 
	in_image, 
	out_valid, 
	out_image);
   input clk;
   input rst_n;
   input in_valid;
   input [7:0] in_image;
   output out_valid;
   output [7:0] out_image;

   // Internal wires
   wire FE_OCPN9_C_out_image_0;
   wire C_clk;
   wire C_rst_n;
   wire C_in_valid;
   wire [7:0] C_in_image;
   wire C_out_valid;
   wire [7:0] C_out_image;

   BUFX2 FE_OCPC11_C_out_image_0 (.A(C_out_image[0]),
	.Y(FE_OCPN9_C_out_image_0));
   LBP U_LBP (.clk(C_clk),
	.rst_n(C_rst_n),
	.in_valid(C_in_valid),
	.in_image(C_in_image),
	.out_valid(C_out_valid),
	.out_image(C_out_image));
   P8C I_CLK (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b0),
	.CSEN(1'b1),
	.Y(C_clk),
	.P(clk));
   P8C I_RESET (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_rst_n),
	.P(rst_n));
   P4C I_VALID (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_valid),
	.P(in_valid));
   P4C I_IN_0 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[0]),
	.P(in_image[0]));
   P4C I_IN_1 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[1]),
	.P(in_image[1]));
   P4C I_IN_2 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[2]),
	.P(in_image[2]));
   P4C I_IN_3 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[3]),
	.P(in_image[3]));
   P4C I_IN_4 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[4]),
	.P(in_image[4]));
   P4C I_IN_5 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[5]),
	.P(in_image[5]));
   P4C I_IN_6 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[6]),
	.P(in_image[6]));
   P4C I_IN_7 (.A(1'b0),
	.ODEN(1'b0),
	.OCEN(1'b0),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.Y(C_in_image[7]),
	.P(in_image[7]));
   P8C O_VALID (.A(C_out_valid),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_valid));
   P8C O_OUT_0 (.A(FE_OCPN9_C_out_image_0),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[0]));
   P8C O_OUT_1 (.A(C_out_image[1]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[1]));
   P8C O_OUT_2 (.A(C_out_image[2]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[2]));
   P8C O_OUT_3 (.A(C_out_image[3]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[3]));
   P8C O_OUT_4 (.A(C_out_image[4]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[4]));
   P8C O_OUT_5 (.A(C_out_image[5]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[5]));
   P8C O_OUT_6 (.A(C_out_image[6]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[6]));
   P8C O_OUT_7 (.A(C_out_image[7]),
	.ODEN(1'b1),
	.OCEN(1'b1),
	.PU(1'b1),
	.PD(1'b0),
	.CEN(1'b1),
	.CSEN(1'b0),
	.P(out_image[7]));
   PVDDR VDDP0 ();
   PVSSR GNDP0 ();
   PVDDR VDDP1 ();
   PVSSR GNDP1 ();
   PVDDR VDDP2 ();
   PVSSR GNDP2 ();
   PVDDR VDDP3 ();
   PVSSR GNDP3 ();
   PVDDR VDDP4 ();
   PVSSR GNDP4 ();
   PVDDR VDDP5 ();
   PVSSR GNDP5 ();
   PVDDR VDDP6 ();
   PVSSR GNDP6 ();
   PVDDR VDDP7 ();
   PVSSR GNDP7 ();
   PVDDC VDDC0 ();
   PVSSC GNDC0 ();
   PVDDC VDDC1 ();
   PVSSC GNDC1 ();
   PVDDC VDDC2 ();
   PVSSC GNDC2 ();
   PVDDC VDDC3 ();
   PVSSC GNDC3 ();
   PVDDC VDDC4 ();
   PVSSC GNDC4 ();
   PVDDC VDDC5 ();
   PVSSC GNDC5 ();
   PVDDC VDDC6 ();
   PVSSC GNDC6 ();
   PVDDC VDDC7 ();
   PVSSC GNDC7 ();
endmodule

